# Generated by Django 4.1 on 2022-08-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=100),
        ),
    ]
