# Generated by Django 4.1.2 on 2022-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apitask", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
