# Generated by Django 4.1.2 on 2022-11-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apitask", "0003_remove_task_description_remove_task_title_task_body"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="body",),
        migrations.AddField(
            model_name="task", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
